version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_USER: ticket_user
      POSTGRES_PASSWORD: ticket
      POSTGRES_DB: ticket_db
      TZ: Asia/Kolkata

  adminer:
    image: adminer:latest
    container_name: adminer_ui
    restart: always
    ports:
      - "8088:8080"


  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak_server
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
    volumes:
      - keycloak-data:/opt/keycloak/data
    command:
        - start-dev
        - --db=dev-file
    ports:
      - "9091:8080"


volumes:
  keycloak-data:
    driver: local